-- Tarefa 06 (23/03/2024)
-- Criando a tabela EMPLOYEES (Funcionários)

CREATE TABLE EMPLOYEES(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME VARCHAR(100) NOT NULL,
  PHONE VARCHAR(16) NOT NULL,
  CONTRACT_TIME DATETIME NOT NULL,
  POSITION_ID INTEGER NOT NULL,
  
  FOREIGN KEY (POSITION_ID) REFERENCES POSITIONS(ID)
);
